version: "3.7"
services: 
  traefik:
    image: traefik:v2.2
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    networks: 
      - traefik-network
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./cert:/cert
      - ./config:/etc/traefik:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  traefik-network:
    name: traefik-network
    driver: overlay
    driver_opts: 
      encrypted: ""
   