http:
  middlewares:
    security-header-middleware:
      headers:
        customResponseHeaders:
          server: _
        contentTypeNosniff: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
